apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dongyu-tan/learning-k8s.git
    targetRevision: main
    path: phase-2/atlas/charts/api-service
    helm:
      parameters:
        - name: image.repository
          value: 381492214245.dkr.ecr.ap-southeast-5.amazonaws.com/capstone-1-api
        - name: image.tag
          value: cef84c1
        - name: image.pullPolicy
          value: IfNotPresent
        - name: ingress.enabled
          value: "false"
        - name: secret.create
          value: "false"
        - name: secret.name
          value: atlas-api-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: atlas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
