apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-worker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dongyu-tan/learning-k8s.git
    targetRevision: main
    path: phase-2/atlas/charts/worker
    helm:
      parameters:
        - name: image.repository
          value: 381492214245.dkr.ecr.ap-southeast-5.amazonaws.com/capstone-1-worker
        - name: image.tag
          value: 6ea63b1
        - name: image.pullPolicy
          value: IfNotPresent
        - name: secret.create
          value: "false"
        - name: secret.name
          value: atlas-worker-secret
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::381492214245:role/capstone-1-worker
  destination:
    server: https://kubernetes.default.svc
    namespace: atlas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
